### ISSUE TITLE
Errors on compiling

### ISSUE THREAD

**Issue by itemsCenter** [kraj011/DiscordAuthBotV2#1]
Hi,

every time I try to run your script I get these error messages, i have no clue what im doing wrong but i'd be glad for any help or assistance.
<img width="514" alt="screenshot 2019-02-27 at 00 49 09" src="https://user-images.githubusercontent.com/26344980/53455121-b8340d80-3a29-11e9-8034-b0c9e60d3bbe.png">

**Comment by itemsCenter** [comment]
> Hi,
> 
> every time I try to run your script I get these error messages, i have no clue what im doing wrong but i'd be glad for any help or assistance.
> 

I tried it on Mac & Windows but both are having same errors.

**Comment by kraj011** [comment]
Hey unfortunately I never actually got a chance to finish this project. I’ll try my best to get it finished by this week! In the meantime you can use my version 1 (just look through my repositories) which works perfectly fine as of right now. Check back again this weekend or next week and this version should be good to go :)
