### ISSUE TITLE
Failed to compile, error message.

### ISSUE THREAD

**Issue by itemsCenter** [kraj011/DiscordAuthBotV2#2]
Hi,

can you please help me how to figure out this error, tried it on my Ubuntu server and Windows desktop as well but nothing works.

<img width="803" alt="screenshot 2019-03-03 at 12 51 56" src="https://user-images.githubusercontent.com/26344980/53696015-f97a4380-3dc2-11e9-966c-67fa69665494.png">

Thank you

**Comment by itemsCenter** [comment]
> Hi,
> 
> can you please help me how to figure out this error, tried it on my Ubuntu server and Windows desktop as well but nothing works.
> 
> 
> Thank you

I installed the "fs" package.. I tried npm install fs & npm install --save fs but I'm still getting this error message.

**Comment by kraj011** [comment]
Hey there’s a bug in the current version I haven’t had time to fix. I will fix it now, but keep in mind in the current version you will not be able to unbind keys through the dashboard.
