### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by R2Riccardo** [kraj011/DiscordAuthBotV2#3]
MacBook-Pro-RR:discordauthbotv2-master riccardo$ sudo npm run develop

> DiscordAuthBotV2@1.0.0 develop /Users/riccardo/Downloads/DiscordAuthBotV2-master
> gatsby develop | node ./src/scripts/runDiscord.js

I am ready!
error Unable to find plugin "gatsby-transformer-sharp". Perhaps you need to install its package?
error UNHANDLED REJECTION

**Comment by 2020iscancelled** [comment]
install gatsby-transformer-sharp u nonce

**Comment by kraj011** [comment]
uhhhh yea so like i redid alot of the stuff so redownload the auth bot and you should be good to go. working on some more improvements rn aswell.
