### ISSUE TITLE
Error RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pierrecdlc** [kraj011/DiscordAuthBotV2#5]
Hello, 
This is my SSH 
When I run the host:8001 I got : Cannot GET/

root@SMC-03-BACKUP1:~/dash# npm start

> DiscordAuthBotV2@1.0.0 start /root/dash
> concurrently "gatsby develop" "node ./src/scripts/runDiscord.js" "node ./src/scripts/localApi.js"

[2] Local Api started on port 8001!
[1] Discord AUTH BOT running!
success open and validate gatsby-configs - 0.011 s
success load plugins - 0.384 s
success onPreInit - 0.007 s
success initialize cache - 0.009 s
success copy gatsby files - 0.020 s
success onPreBootstrap - 0.021 s
success source and transform nodes - 0.051 s
success building schema - 0.303 s
success createPages - 0.002 s
success createPagesStatefully - 0.053 s
success onPreExtractQueries - 0.004 s
success update schema - 0.041 s
success extract queries from components - 0.212 s
success write out requires - 0.005 s
success write out redirect data - 0.007 s
success Build manifest and related icons - 0.420 s
success onPostBootstrap - 0.435 s
⠀
info bootstrap finished - 4.911 s
⠀
success run static queries - 0.052 s — 2/2 42.56 queries/second
success run page queries - 0.030 s — 7/7 262.05 queries/second
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
 DONE  Compiled successfully in 17122ms10:47:30 PM
⠀

You can now view DiscordAuthBotV2 in the browser.
[0] 
⠀
[0] 
  http://localhost:8000/
[0] 
⠀
[0] 
View GraphiQL, an in-browser IDE, to explore your site's data and schema
[0] 
⠀
[0] 
  http://localhost:8000/___graphql
[0] 
⠀
[0] 
Note that the development build is not optimized.
[0] 
To create a production build, use npm run build
[0] 
⠀
[0] 
ℹ ｢wdm｣:
[0] 
ℹ ｢wdm｣: Compiled successfully.
[0] 

[0] 
[0] 7 pages                                                                         
[0]     DiscordAuthBotV2

**Comment by kraj011** [comment]
Are you trying to open the dashboard? if so, open port 8000 and not 8001. See if that works.

**Comment by pierrecdlc** [comment]
It’s not working, got a « can’t reach server » on port 8000

**Comment by pierrecdlc** [comment]
I m running unbuntu, node npm and yarn updated (server, digital ocean)

**Comment by pierrecdlc** [comment]
@kraj011 Can you please add me on discord, I have a freelance job for you, +need help,
Thanks
My discord : xxpierre#1154

**Comment by kraj011** [comment]
For future reference: issue was with server, not with project itself. Closing this issue.
